### ISSUE TITLE
fieldset is incorrect on the DocumentGenerator

### ISSUE THREAD

**Issue by ryansheehan** [rdunk/sanity-schema-builder#1]
The DocumentGenerator is relying on the StandardGenerator to create a fieldset.  The StandardGenerator is making a fieldset as single string to attach to a field instead of the `{name: string, title?: string}` that the SchemaGenerator produces.   As far as I can tell there is no way to attach a fieldset property to the Document.

**Comment by rdunk** [comment]
Thanks for noticing that. I've just published [v0.1.3](https://github.com/rdunk/sanity-schema-builder/releases/tag/v0.1.3) with a fix. Let me know if that solves it for you.

**Comment by rdunk** [comment]
Assuming fixed. Please reopen if you're still encountering the issue, and thanks for reporting it.
